services:
- name: identity
  id: 1
  actions:
  - name: login
    id: 1
    rate_limit:
    - name: default
      unit: minutes
      unit_multiplier: 2
      request_per_unit: 3
      algorithm: fixed_window

    - name: basic
      unit: minutes
      unit_multiplier: 1
      request_per_unit: 10
      algorithm: sliding_window

    - name: premium
      unit: hours
      unit_multiplier: 1
      request_per_unit: 20
      algorithm: fixed_window

  - name: signUp
    id: 2
    rate_limit:
    - name: default
      unit: hours
      unit_multiplier: 1
      request_per_unit: 2
      algorithm: fixed_window

  - name: changePassword
    id: 3
    rate_limit:
    - name: default
      unit: hours
      unit_multiplier: 1
      request_per_unit: 1
      algorithm: fixed_window

  - name: forgotPassword
    id: 4
    rate_limit:
    - name: default
      unit: hours
      unit_multiplier: 1
      request_per_unit: 1
      algorithm: fixed_window

  - name: disscord
    id: 2
    actions:
    - name: sendMessage
      id: 1
      rate_limit:
      - name: default
        unit: minutes
        unit_multiplier: 1
        request_per_unit: 60
        algorithm: fixed_window

      - name: nitro
        unit: minutes
        unit_multiplier: 1
        request_per_unit: 120
        algorithm: sliding_window

    - name: changeGroupName
      id: 2
      rate_limit:
      - name: default
        unit: hours
        unit_multiplier: 1
        request_per_unit: 1
        algorithm: fixed_window

      - name: nitro
        unit: minutes
        unit_multiplier: 1
        request_per_unit: 2
        algorithm: sliding_window
